//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GeneralAccount {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralAccount() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.GeneralAccount", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusted Trial Balance.
        /// </summary>
        internal static string AdjustedTrialBalance {
            get {
                return ResourceManager.GetString("AdjustedTrialBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Flow List.
        /// </summary>
        internal static string CashFlowList {
            get {
                return ResourceManager.GetString("CashFlowList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Of Accounts.
        /// </summary>
        internal static string ChartOfAccounts {
            get {
                return ResourceManager.GetString("ChartOfAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Entries.
        /// </summary>
        internal static string DailyEntries {
            get {
                return ResourceManager.GetString("DailyEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income Statement.
        /// </summary>
        internal static string IncomeStatement {
            get {
                return ResourceManager.GetString("IncomeStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ledger Account.
        /// </summary>
        internal static string LedgerAccount {
            get {
                return ResourceManager.GetString("LedgerAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Entry Papers.
        /// </summary>
        internal static string PaymentEntryPapers {
            get {
                return ResourceManager.GetString("PaymentEntryPapers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payments Entry.
        /// </summary>
        internal static string PaymentsEntry {
            get {
                return ResourceManager.GetString("PaymentsEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchases Entry.
        /// </summary>
        internal static string PurchasesEntry {
            get {
                return ResourceManager.GetString("PurchasesEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReceiptsEntry.
        /// </summary>
        internal static string ReceiptsEntry {
            get {
                return ResourceManager.GetString("ReceiptsEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary Entry Papers.
        /// </summary>
        internal static string SalaryEntryPapers {
            get {
                return ResourceManager.GetString("SalaryEntryPapers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Entry.
        /// </summary>
        internal static string SalesEntry {
            get {
                return ResourceManager.GetString("SalesEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement Of Financial Position.
        /// </summary>
        internal static string StatementOfFinancialPosition {
            get {
                return ResourceManager.GetString("StatementOfFinancialPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subsidiary Ledger.
        /// </summary>
        internal static string SubsidiaryLedger {
            get {
                return ResourceManager.GetString("SubsidiaryLedger", resourceCulture);
            }
        }
    }
}
