//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Store {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Store() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Store", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Branch.
        /// </summary>
        internal static string AddBranch {
            get {
                return ResourceManager.GetString("AddBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add CarChangeRateOnDis.
        /// </summary>
        internal static string AddCarChangeRateOnDis {
            get {
                return ResourceManager.GetString("AddCarChangeRateOnDis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أضــافة خـدمـة ســيـارة .
        /// </summary>
        internal static string AddCarMaintenance {
            get {
                return ResourceManager.GetString("AddCarMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أضافة ســـيـارة.
        /// </summary>
        internal static string AddCars {
            get {
                return ResourceManager.GetString("AddCars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Car Type.
        /// </summary>
        internal static string AddCarType {
            get {
                return ResourceManager.GetString("AddCarType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Category.
        /// </summary>
        internal static string AddCategory {
            get {
                return ResourceManager.GetString("AddCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add City.
        /// </summary>
        internal static string AddCity {
            get {
                return ResourceManager.GetString("AddCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Client.
        /// </summary>
        internal static string AddClient {
            get {
                return ResourceManager.GetString("AddClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Colors.
        /// </summary>
        internal static string AddColors {
            get {
                return ResourceManager.GetString("AddColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Driver.
        /// </summary>
        internal static string AddDriver {
            get {
                return ResourceManager.GetString("AddDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add From Region.
        /// </summary>
        internal static string AddFromRegion {
            get {
                return ResourceManager.GetString("AddFromRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add ListPrice.
        /// </summary>
        internal static string AddListPrice {
            get {
                return ResourceManager.GetString("AddListPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Product.
        /// </summary>
        internal static string AddProduct {
            get {
                return ResourceManager.GetString("AddProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Address filed is required.
        /// </summary>
        internal static string AddressEM {
            get {
                return ResourceManager.GetString("AddressEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Address.
        /// </summary>
        internal static string AddressPH {
            get {
                return ResourceManager.GetString("AddressPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Role.
        /// </summary>
        internal static string AddRole {
            get {
                return ResourceManager.GetString("AddRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Service.
        /// </summary>
        internal static string AddService {
            get {
                return ResourceManager.GetString("AddService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أضــافة خــدمــة.
        /// </summary>
        internal static string AddServices {
            get {
                return ResourceManager.GetString("AddServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Store.
        /// </summary>
        internal static string AddStore {
            get {
                return ResourceManager.GetString("AddStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Transport Command.
        /// </summary>
        internal static string AddTransportCommand {
            get {
                return ResourceManager.GetString("AddTransportCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Unit.
        /// </summary>
        internal static string AddUnit {
            get {
                return ResourceManager.GetString("AddUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speedometer Read After.
        /// </summary>
        internal static string After {
            get {
                return ResourceManager.GetString("After", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Speedometer Read After filed is required..
        /// </summary>
        internal static string AfterEM {
            get {
                return ResourceManager.GetString("AfterEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert Period.
        /// </summary>
        internal static string AlertPeriod {
            get {
                return ResourceManager.GetString("AlertPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Alert Period filed is required..
        /// </summary>
        internal static string AlertPeriodEM {
            get {
                return ResourceManager.GetString("AlertPeriodEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Alert Period.
        /// </summary>
        internal static string AlertPeriodPH {
            get {
                return ResourceManager.GetString("AlertPeriodPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مـــعـدل تـنـبـيـة التـــغــييـر .
        /// </summary>
        internal static string AlertRate {
            get {
                return ResourceManager.GetString("AlertRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another Material Name.
        /// </summary>
        internal static string AnotherMaterialName {
            get {
                return ResourceManager.GetString("AnotherMaterialName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At Hour.
        /// </summary>
        internal static string AtHour {
            get {
                return ResourceManager.GetString("AtHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخل الــســاعة.
        /// </summary>
        internal static string AtHourEM {
            get {
                return ResourceManager.GetString("AtHourEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الــمــعــدل.
        /// </summary>
        internal static string Average {
            get {
                return ResourceManager.GetString("Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speedometer Read Before.
        /// </summary>
        internal static string Before {
            get {
                return ResourceManager.GetString("Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Speedometer Read Before filed is required..
        /// </summary>
        internal static string BeforeEM {
            get {
                return ResourceManager.GetString("BeforeEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch name.
        /// </summary>
        internal static string BranchName {
            get {
                return ResourceManager.GetString("BranchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Card.
        /// </summary>
        internal static string BrandCard {
            get {
                return ResourceManager.GetString("BrandCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CarChangeRateOnDis.
        /// </summary>
        internal static string CarChangeRateOnDis {
            get {
                return ResourceManager.GetString("CarChangeRateOnDis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خــدمـات صــيانـة الـسـيـارات.
        /// </summary>
        internal static string CarMaintenance {
            get {
                return ResourceManager.GetString("CarMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقـــم الــسـيارة.
        /// </summary>
        internal static string CarNo {
            get {
                return ResourceManager.GetString("CarNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بــرجـاء أدخـل رقــم الــسـيـارة.
        /// </summary>
        internal static string CarNoEM {
            get {
                return ResourceManager.GetString("CarNoEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدخـل رقـــم الــسـيارة.
        /// </summary>
        internal static string CarNoPH {
            get {
                return ResourceManager.GetString("CarNoPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الـسـيـارات.
        /// </summary>
        internal static string Cars {
            get {
                return ResourceManager.GetString("Cars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نــوع الـسـيـارة.
        /// </summary>
        internal static string CarType {
            get {
                return ResourceManager.GetString("CarType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to categorys.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to category name.
        /// </summary>
        internal static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مــعــدل تـغـييـر .
        /// </summary>
        internal static string ChangeRate {
            get {
                return ResourceManager.GetString("ChangeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        internal static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chopping.
        /// </summary>
        internal static string Chopping {
            get {
                return ResourceManager.GetString("Chopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الـمديـنـة.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أســـم الــعــمـيـل.
        /// </summary>
        internal static string ClientName {
            get {
                return ResourceManager.GetString("ClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Type.
        /// </summary>
        internal static string ClientType {
            get {
                return ResourceManager.GetString("ClientType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اللون.
        /// </summary>
        internal static string Colors {
            get {
                return ResourceManager.GetString("Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Order Number.
        /// </summary>
        internal static string CommandOrderNo {
            get {
                return ResourceManager.GetString("CommandOrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CommandOrderNo Filed Is Required..
        /// </summary>
        internal static string CommandOrderNoEM {
            get {
                return ResourceManager.GetString("CommandOrderNoEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Order Operation.
        /// </summary>
        internal static string CommandOrderOper {
            get {
                return ResourceManager.GetString("CommandOrderOper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Orders.
        /// </summary>
        internal static string CommandOrders {
            get {
                return ResourceManager.GetString("CommandOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication Method.
        /// </summary>
        internal static string CommunicationMethod {
            get {
                return ResourceManager.GetString("CommunicationMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Code.
        /// </summary>
        internal static string CompanyCode {
            get {
                return ResourceManager.GetString("CompanyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Company Code Files Is Required..
        /// </summary>
        internal static string CompanyCodeEM {
            get {
                return ResourceManager.GetString("CompanyCodeEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        internal static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Count filed is required..
        /// </summary>
        internal static string CountEM {
            get {
                return ResourceManager.GetString("CountEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرصيد الأفــتتاحي.
        /// </summary>
        internal static string CurrentBalance {
            get {
                return ResourceManager.GetString("CurrentBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخــل الرصيد الأفــتتاحي.
        /// </summary>
        internal static string CurrentBalanceEM {
            get {
                return ResourceManager.GetString("CurrentBalanceEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القراءة الحالية.
        /// </summary>
        internal static string CurrentReading {
            get {
                return ResourceManager.GetString("CurrentReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Balances.
        /// </summary>
        internal static string CustomerBalances {
            get {
                return ResourceManager.GetString("CustomerBalances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Or Company.
        /// </summary>
        internal static string CustomerOrCompany {
            get {
                return ResourceManager.GetString("CustomerOrCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        internal static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Statement.
        /// </summary>
        internal static string CustomerStatement {
            get {
                return ResourceManager.GetString("CustomerStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Date Filed Is Required..
        /// </summary>
        internal static string DateEM {
            get {
                return ResourceManager.GetString("DateEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date From.
        /// </summary>
        internal static string DateFrom {
            get {
                return ResourceManager.GetString("DateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Transport.
        /// </summary>
        internal static string DateOfTransport {
            get {
                return ResourceManager.GetString("DateOfTransport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date To.
        /// </summary>
        internal static string DateTo {
            get {
                return ResourceManager.GetString("DateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design Order.
        /// </summary>
        internal static string DesignOrder {
            get {
                return ResourceManager.GetString("DesignOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design Order Operation.
        /// </summary>
        internal static string DesignOrderOper {
            get {
                return ResourceManager.GetString("DesignOrderOper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discarded.
        /// </summary>
        internal static string Discarded {
            get {
                return ResourceManager.GetString("Discarded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        internal static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Type.
        /// </summary>
        internal static string DiscountType {
            get {
                return ResourceManager.GetString("DiscountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المسافة المقطوعة.
        /// </summary>
        internal static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drivers.
        /// </summary>
        internal static string Driver {
            get {
                return ResourceManager.GetString("Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The E-mail Files Is Required..
        /// </summary>
        internal static string EmailEM {
            get {
                return ResourceManager.GetString("EmailEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must Enter Vaild E-mail ..
        /// </summary>
        internal static string EmailEMR {
            get {
                return ResourceManager.GetString("EmailEMR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Name.
        /// </summary>
        internal static string EmployeeName {
            get {
                return ResourceManager.GetString("EmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excution Order Operation.
        /// </summary>
        internal static string ExcutionOrderOper {
            get {
                return ResourceManager.GetString("ExcutionOrderOper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution Order.
        /// </summary>
        internal static string ExecutionOrder {
            get {
                return ResourceManager.GetString("ExecutionOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to executor.
        /// </summary>
        internal static string executor {
            get {
                return ResourceManager.GetString("executor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by Product Name.
        /// </summary>
        internal static string FilterbyProductName {
            get {
                return ResourceManager.GetString("FilterbyProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادخل جزء من أسم الصنف.
        /// </summary>
        internal static string FilterbyProductNamePH {
            get {
                return ResourceManager.GetString("FilterbyProductNamePH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Total Page.
        /// </summary>
        internal static string FinalTotal {
            get {
                return ResourceManager.GetString("FinalTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Total Operation.
        /// </summary>
        internal static string FinalTotalOper {
            get {
                return ResourceManager.GetString("FinalTotalOper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        internal static string FromRegion {
            get {
                return ResourceManager.GetString("FromRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Data.
        /// </summary>
        internal static string GetData {
            get {
                return ResourceManager.GetString("GetData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Location.
        /// </summary>
        internal static string GetLocation {
            get {
                return ResourceManager.GetString("GetLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Rows Available.
        /// </summary>
        internal static string GridNoRows {
            get {
                return ResourceManager.GetString("GridNoRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hanging.
        /// </summary>
        internal static string hanging {
            get {
                return ResourceManager.GetString("hanging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has size.
        /// </summary>
        internal static string HasSize {
            get {
                return ResourceManager.GetString("HasSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indebtedness.
        /// </summary>
        internal static string Indebtedness {
            get {
                return ResourceManager.GetString("Indebtedness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        internal static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Date.
        /// </summary>
        internal static string InvoiceDate {
            get {
                return ResourceManager.GetString("InvoiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Number.
        /// </summary>
        internal static string InvoiceNo {
            get {
                return ResourceManager.GetString("InvoiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoices Reports.
        /// </summary>
        internal static string InvoicesReports {
            get {
                return ResourceManager.GetString("InvoicesReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Outgoing.
        /// </summary>
        internal static string ItemOutgoing {
            get {
                return ResourceManager.GetString("ItemOutgoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Receipts.
        /// </summary>
        internal static string ItemReceipts {
            get {
                return ResourceManager.GetString("ItemReceipts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القراءة السابقة.
        /// </summary>
        internal static string LastReading {
            get {
                return ResourceManager.GetString("LastReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        internal static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lenght.
        /// </summary>
        internal static string Lenght {
            get {
                return ResourceManager.GetString("Lenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the Lenght filed is required..
        /// </summary>
        internal static string LenghtEM {
            get {
                return ResourceManager.GetString("LenghtEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licence Date.
        /// </summary>
        internal static string LicenceDate {
            get {
                return ResourceManager.GetString("LicenceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licence Date filed is required..
        /// </summary>
        internal static string LicenceDateEM {
            get {
                return ResourceManager.GetString("LicenceDateEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Licence Date.
        /// </summary>
        internal static string LicenceDatePH {
            get {
                return ResourceManager.GetString("LicenceDatePH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقــم الرخـصه.
        /// </summary>
        internal static string LicenceNO {
            get {
                return ResourceManager.GetString("LicenceNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بــرجـاء أدخـل رقــم الرخـصه.
        /// </summary>
        internal static string LicenceNOEM {
            get {
                return ResourceManager.GetString("LicenceNOEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدخـل رقــم الرخـصه.
        /// </summary>
        internal static string LicenceNOPH {
            get {
                return ResourceManager.GetString("LicenceNOPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licence Period.
        /// </summary>
        internal static string LicencePeriod {
            get {
                return ResourceManager.GetString("LicencePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licence Period filed is required..
        /// </summary>
        internal static string LicencePeriodEM {
            get {
                return ResourceManager.GetString("LicencePeriodEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Licence Period.
        /// </summary>
        internal static string LicencePeriodPH {
            get {
                return ResourceManager.GetString("LicencePeriodPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        internal static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The License filed is required..
        /// </summary>
        internal static string LicenseEM {
            get {
                return ResourceManager.GetString("LicenseEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License End Date.
        /// </summary>
        internal static string LicenseEndDate {
            get {
                return ResourceManager.GetString("LicenseEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter License.
        /// </summary>
        internal static string LicensePH {
            get {
                return ResourceManager.GetString("LicensePH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListPrice.
        /// </summary>
        internal static string ListPrice {
            get {
                return ResourceManager.GetString("ListPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        internal static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Look Ups.
        /// </summary>
        internal static string LookUpsViews {
            get {
                return ResourceManager.GetString("LookUpsViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Type.
        /// </summary>
        internal static string MachineType {
            get {
                return ResourceManager.GetString("MachineType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturing Materials.
        /// </summary>
        internal static string ManufacturingMaterials {
            get {
                return ResourceManager.GetString("ManufacturingMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Name.
        /// </summary>
        internal static string MaterialName {
            get {
                return ResourceManager.GetString("MaterialName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Balance.
        /// </summary>
        internal static string MinBalance {
            get {
                return ResourceManager.GetString("MinBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Min Balance filed is required..
        /// </summary>
        internal static string MinBalanceEM {
            get {
                return ResourceManager.GetString("MinBalanceEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name filed is required.
        /// </summary>
        internal static string NameEM {
            get {
                return ResourceManager.GetString("NameEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter name.
        /// </summary>
        internal static string NamePH {
            get {
                return ResourceManager.GetString("NamePH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Search.
        /// </summary>
        internal static string NewSearch {
            get {
                return ResourceManager.GetString("NewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not has size.
        /// </summary>
        internal static string NotHasSize {
            get {
                return ResourceManager.GetString("NotHasSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Voided.
        /// </summary>
        internal static string NotVoided {
            get {
                return ResourceManager.GetString("NotVoided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Details.
        /// </summary>
        internal static string OperationDetails {
            get {
                return ResourceManager.GetString("OperationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Name.
        /// </summary>
        internal static string OperationName {
            get {
                return ResourceManager.GetString("OperationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The OperationName Filed Is Required..
        /// </summary>
        internal static string OperationNameEM {
            get {
                return ResourceManager.GetString("OperationNameEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Command .
        /// </summary>
        internal static string OrderCommand {
            get {
                return ResourceManager.GetString("OrderCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Number.
        /// </summary>
        internal static string OrderNo {
            get {
                return ResourceManager.GetString("OrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outgoing .
        /// </summary>
        internal static string OutgoingPermission {
            get {
                return ResourceManager.GetString("OutgoingPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Password filed is required..
        /// </summary>
        internal static string PasswordEM {
            get {
                return ResourceManager.GetString("PasswordEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طـــريــقــة الــدفــع.
        /// </summary>
        internal static string PaymentMethod {
            get {
                return ResourceManager.GetString("PaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Value.
        /// </summary>
        internal static string PaymentValue {
            get {
                return ResourceManager.GetString("PaymentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage.
        /// </summary>
        internal static string Percentage {
            get {
                return ResourceManager.GetString("Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the phone filed is required.
        /// </summary>
        internal static string PhoneEMR {
            get {
                return ResourceManager.GetString("PhoneEMR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this filed must be phone number.
        /// </summary>
        internal static string PhoneEMV {
            get {
                return ResourceManager.GetString("PhoneEMV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Phone ex: 201xxxxxxxxx.
        /// </summary>
        internal static string PhonePH {
            get {
                return ResourceManager.GetString("PhonePH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Price.
        /// </summary>
        internal static string PPrice {
            get {
                return ResourceManager.GetString("PPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Purchase Price filed is required..
        /// </summary>
        internal static string PPriceEM {
            get {
                return ResourceManager.GetString("PPriceEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparation.
        /// </summary>
        internal static string Preparation {
            get {
                return ResourceManager.GetString("Preparation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Price filed is required..
        /// </summary>
        internal static string PriceEM {
            get {
                return ResourceManager.GetString("PriceEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price In Meter.
        /// </summary>
        internal static string PriceInMeter {
            get {
                return ResourceManager.GetString("PriceInMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price In Piece.
        /// </summary>
        internal static string PriceInPiece {
            get {
                return ResourceManager.GetString("PriceInPiece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Per Record.
        /// </summary>
        internal static string PricePerRecord {
            get {
                return ResourceManager.GetString("PricePerRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كود الــصنف.
        /// </summary>
        internal static string ProductID {
            get {
                return ResourceManager.GetString("ProductID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بــرجاء أدخــل كود الــصنف .
        /// </summary>
        internal static string ProductIDEM {
            get {
                return ResourceManager.GetString("ProductIDEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادخل كود الــصنف.
        /// </summary>
        internal static string ProductIDPH {
            get {
                return ResourceManager.GetString("ProductIDPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        internal static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Price.
        /// </summary>
        internal static string ProductPrice {
            get {
                return ResourceManager.GetString("ProductPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Product Price filed is required..
        /// </summary>
        internal static string ProductPriceEM {
            get {
                return ResourceManager.GetString("ProductPriceEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entre Product Price.
        /// </summary>
        internal static string ProductPricePH {
            get {
                return ResourceManager.GetString("ProductPricePH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        internal static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Type.
        /// </summary>
        internal static string ProductType {
            get {
                return ResourceManager.GetString("ProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to profile.
        /// </summary>
        internal static string profile {
            get {
                return ResourceManager.GetString("profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pruchase Invoice Report.
        /// </summary>
        internal static string PruchaseInvoiceReport {
            get {
                return ResourceManager.GetString("PruchaseInvoiceReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase.
        /// </summary>
        internal static string Purchase {
            get {
                return ResourceManager.GetString("Purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أذن اسـتـلام بــضـاعـة.
        /// </summary>
        internal static string PurchaseInvoice {
            get {
                return ResourceManager.GetString("PurchaseInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Invoices.
        /// </summary>
        internal static string PurchaseInvoices {
            get {
                return ResourceManager.GetString("PurchaseInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Invoice With Detail Report.
        /// </summary>
        internal static string PurchaseInvoiceWithDetailReport {
            get {
                return ResourceManager.GetString("PurchaseInvoiceWithDetailReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Invoice Type.
        /// </summary>
        internal static string PurchaseType {
            get {
                return ResourceManager.GetString("PurchaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string Qty {
            get {
                return ResourceManager.GetString("Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the Quntity filed is required..
        /// </summary>
        internal static string QtyEM {
            get {
                return ResourceManager.GetString("QtyEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt Date.
        /// </summary>
        internal static string ReceiptDate {
            get {
                return ResourceManager.GetString("ReceiptDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt Place.
        /// </summary>
        internal static string ReceiptPlace {
            get {
                return ResourceManager.GetString("ReceiptPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region From.
        /// </summary>
        internal static string RegionFrom {
            get {
                return ResourceManager.GetString("RegionFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region To.
        /// </summary>
        internal static string RegionTo {
            get {
                return ResourceManager.GetString("RegionTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviewer.
        /// </summary>
        internal static string Reviewer {
            get {
                return ResourceManager.GetString("Reviewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Reviewer filed is required..
        /// </summary>
        internal static string ReviewerEM {
            get {
                return ResourceManager.GetString("ReviewerEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale.
        /// </summary>
        internal static string Sale {
            get {
                return ResourceManager.GetString("Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Invoice.
        /// </summary>
        internal static string SaleInvoice {
            get {
                return ResourceManager.GetString("SaleInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Invoices.
        /// </summary>
        internal static string SaleInvoices {
            get {
                return ResourceManager.GetString("SaleInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Invoices Oper..
        /// </summary>
        internal static string SaleInvoicesOper {
            get {
                return ResourceManager.GetString("SaleInvoicesOper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Movement.
        /// </summary>
        internal static string SalesMovement {
            get {
                return ResourceManager.GetString("SalesMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Name.
        /// </summary>
        internal static string SalesName {
            get {
                return ResourceManager.GetString("SalesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Sales Name Files Is Required..
        /// </summary>
        internal static string SalesNameEM {
            get {
                return ResourceManager.GetString("SalesNameEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Invoice Type.
        /// </summary>
        internal static string SaleType {
            get {
                return ResourceManager.GetString("SaleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Command Order.
        /// </summary>
        internal static string SelectCommandOrder {
            get {
                return ResourceManager.GetString("SelectCommandOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service name.
        /// </summary>
        internal static string ServiceName {
            get {
                return ResourceManager.GetString("ServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Type.
        /// </summary>
        internal static string ServiceType {
            get {
                return ResourceManager.GetString("ServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Service Type filed is required..
        /// </summary>
        internal static string ServiceTypeEM {
            get {
                return ResourceManager.GetString("ServiceTypeEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size State.
        /// </summary>
        internal static string SizeState {
            get {
                return ResourceManager.GetString("SizeState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solar Or Oil Report.
        /// </summary>
        internal static string SolarOrOilReport {
            get {
                return ResourceManager.GetString("SolarOrOilReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كمية السولار او البنزين.
        /// </summary>
        internal static string SolarQty {
            get {
                return ResourceManager.GetString("SolarQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Price.
        /// </summary>
        internal static string SPrice {
            get {
                return ResourceManager.GetString("SPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Sale Price filed is required..
        /// </summary>
        internal static string SPriceEM {
            get {
                return ResourceManager.GetString("SPriceEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Voided.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement.
        /// </summary>
        internal static string Statement {
            get {
                return ResourceManager.GetString("Statement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Statement filed is required..
        /// </summary>
        internal static string StatementEM {
            get {
                return ResourceManager.GetString("StatementEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stocktaking.
        /// </summary>
        internal static string Stocktaking {
            get {
                return ResourceManager.GetString("Stocktaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Name.
        /// </summary>
        internal static string StoreName {
            get {
                return ResourceManager.GetString("StoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubAccount name.
        /// </summary>
        internal static string SubAccountName {
            get {
                return ResourceManager.GetString("SubAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        internal static string Supplier {
            get {
                return ResourceManager.GetString("Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أســـم الـمٌـورد.
        /// </summary>
        internal static string SupplierName {
            get {
                return ResourceManager.GetString("SupplierName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TaxAdded as Percentage (%).
        /// </summary>
        internal static string TaxAdded {
            get {
                return ResourceManager.GetString("TaxAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Added Value.
        /// </summary>
        internal static string TaxAddedValue {
            get {
                return ResourceManager.GetString("TaxAddedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Cost Of Inks.
        /// </summary>
        internal static string TheCostOfInks {
            get {
                return ResourceManager.GetString("TheCostOfInks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thickness.
        /// </summary>
        internal static string thickness {
            get {
                return ResourceManager.GetString("thickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الــسعـر الإجــمالــي للــنــقــل.
        /// </summary>
        internal static string TotalTransportPrice {
            get {
                return ResourceManager.GetString("TotalTransportPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخل الــسعـر الإجــمالــي للــنــقــل.
        /// </summary>
        internal static string TotalTransportPriceEM {
            get {
                return ResourceManager.GetString("TotalTransportPriceEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Traffic Department.
        /// </summary>
        internal static string TrafficDepartment {
            get {
                return ResourceManager.GetString("TrafficDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traffic Department Name.
        /// </summary>
        internal static string TrafficDepartmentName {
            get {
                return ResourceManager.GetString("TrafficDepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Number.
        /// </summary>
        internal static string TransactionNo {
            get {
                return ResourceManager.GetString("TransactionNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كـــود الأذن.
        /// </summary>
        internal static string TransCmdID {
            get {
                return ResourceManager.GetString("TransCmdID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخل كـــود الــنــقل.
        /// </summary>
        internal static string TransCmdIDEM {
            get {
                return ResourceManager.GetString("TransCmdIDEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Type.
        /// </summary>
        internal static string TransferProductType {
            get {
                return ResourceManager.GetString("TransferProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport Command.
        /// </summary>
        internal static string TransportCommand {
            get {
                return ResourceManager.GetString("TransportCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نــوع الــنــقـل.
        /// </summary>
        internal static string TransportType {
            get {
                return ResourceManager.GetString("TransportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أسم الــخـزنــة.
        /// </summary>
        internal static string Treasury {
            get {
                return ResourceManager.GetString("Treasury", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit name.
        /// </summary>
        internal static string UnitName {
            get {
                return ResourceManager.GetString("UnitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used Services.
        /// </summary>
        internal static string UsedServices {
            get {
                return ResourceManager.GetString("UsedServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخل اسم المستخدم.
        /// </summary>
        internal static string UsernameEM {
            get {
                return ResourceManager.GetString("UsernameEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values.
        /// </summary>
        internal static string Values {
            get {
                return ResourceManager.GetString("Values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendors.
        /// </summary>
        internal static string vendors {
            get {
                return ResourceManager.GetString("vendors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voided.
        /// </summary>
        internal static string Voided {
            get {
                return ResourceManager.GetString("Voided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipts.
        /// </summary>
        internal static string WarehouseReceipts {
            get {
                return ResourceManager.GetString("WarehouseReceipts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Width filed is required..
        /// </summary>
        internal static string WidthEM {
            get {
                return ResourceManager.GetString("WidthEM", resourceCulture);
            }
        }
    }
}
